// Placeholder wishlist data (matches EduMaster theme).
// Swap for API data when wishlist endpoints are ready.

export const WISHLIST_ITEMS = [
  {
    id: 'js-ts',
    title: 'Advanced JavaScript & TypeScript Mastery',
    instructor: 'Rahul Sharma',
    category: 'Web Development',
    categoryTint: 'blue',
    art: 'code',
    tint: 'blue',
    rating: 4.8,
    reviews: '2,340',
    price: '₹3,499',
    originalPrice: '₹6,999',
  },
  {
    id: 'ml-az',
    title: 'Machine Learning A–Z with Python',
    instructor: 'Priya Verma',
    category: 'Data Science',
    categoryTint: 'green',
    art: 'chart',
    tint: 'green',
    rating: 4.7,
    reviews: '1,875',
    price: '₹4,299',
    originalPrice: '₹7,999',
  },
  {
    id: 'graphic',
    title: 'Graphic Design Bootcamp: Beginner to Pro',
    instructor: 'Sneha Patel',
    category: 'Design',
    categoryTint: 'purple',
    art: 'design',
    tint: 'purple',
    rating: 4.6,
    reviews: '1,210',
    price: '₹2,999',
    originalPrice: '₹5,499',
  },
  {
    id: 'aws-cloud',
    title: 'Cloud Computing with AWS from Scratch',
    instructor: 'Rohit Kumar',
    category: 'Cloud',
    categoryTint: 'blue',
    art: 'cloud',
    tint: 'blue',
    rating: 4.9,
    reviews: '3,020',
    price: '₹5,499',
    originalPrice: '₹9,999',
  },
]
