import { useEffect, useState } from 'react'
import { createDiscussion, deleteDiscussion, deleteDiscussionReply, getDiscussionReplies, getDiscussions, likeDiscussion, likeDiscussionReply, replyDiscussion, updateDiscussion, updateDiscussionReply } from '../../../api/lms.js'
import DiscussionEditor from './DiscussionEditor.jsx'
import DiscussionItem from './DiscussionItem.jsx'

export default function DiscussionList({ courseId, lessonId, user, updateUser, notify }) {
  const [items, setItems] = useState([]); const [sort, setSort] = useState('newest'); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false)
  const patchItem = (id, callback) => setItems((value) => value.map((item) => item._id === id ? callback(item) : item))
  useEffect(() => { let active = true; setLoading(true); getDiscussions(lessonId, courseId, sort).then((response) => { if (active) setItems(response.data.discussions || []) }).catch((error) => notify(error.message, true)).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [courseId, lessonId, notify, sort])
  const post = async (question) => { setBusy(true); try { const response = await createDiscussion({ courseId, lessonId, question }); setItems((value) => [response.data.discussion, ...value]); if (response.data.stats) updateUser({ stats: response.data.stats }); notify('Question Posted') } catch (error) { notify(error.message, true) } finally { setBusy(false) } }
  const reply = async (id, message) => { try { const response = await replyDiscussion(id, message); patchItem(id, () => response.data.discussion); notify(response.data.notifyAuthor ? 'Reply Received' : 'Reply posted') } catch (error) { notify(error.message, true) } }
  const like = async (id) => { try { const response = await likeDiscussion(id); patchItem(id, (item) => ({ ...item, likesCount: response.data.likesCount, likes: response.data.liked ? [...(item.likes || []), user._id] : (item.likes || []).filter((value) => String(value) !== String(user._id)) })) } catch (error) { notify(error.message, true) } }
  const edit = async (id, question) => { try { const response = await updateDiscussion(id, question); patchItem(id, () => response.data.discussion) } catch (error) { notify(error.message, true) } }
  const remove = async (id) => { try { const response = await deleteDiscussion(id); setItems((value) => value.filter((item) => item._id !== id)); if (response.data.stats) updateUser({ stats: response.data.stats }) } catch (error) { notify(error.message, true) } }
  const loadReplies = async (id) => { const item = items.find((value) => value._id === id); const page = (item?.repliesPage || 1) + 1; try { const response = await getDiscussionReplies(id, page); patchItem(id, (current) => ({ ...current, replies: [...response.data.replies, ...(current.replies || [])], repliesPage: page, hasMoreReplies: page < response.data.pagination.pages })) } catch (error) { notify(error.message, true) } }
  const replyLike = async (id, replyId) => { try { const response = await likeDiscussionReply(id, replyId); patchItem(id, (item) => ({ ...item, replies: item.replies.map((replyItem) => replyItem._id === replyId ? { ...replyItem, likes: response.data.liked ? [...(replyItem.likes || []), user._id] : (replyItem.likes || []).filter((value) => String(value) !== String(user._id)) } : replyItem) })) } catch (error) { notify(error.message, true) } }
  const replyEdit = async (id, replyId, message) => { try { const response = await updateDiscussionReply(id, replyId, message); patchItem(id, () => response.data.discussion) } catch (error) { notify(error.message, true) } }
  const replyDelete = async (id, replyId) => { try { const response = await deleteDiscussionReply(id, replyId); patchItem(id, () => response.data.discussion) } catch (error) { notify(error.message, true) } }
  return <section className="lms-discussion"><div className="lms-discussion-head"><div><h3>Lesson Discussion</h3><p>Ask questions and learn with other students.</p></div><label>Sort <select value={sort} onChange={(event) => setSort(event.target.value)}><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="liked">Most Liked</option></select></label></div><DiscussionEditor onPost={post} busy={busy} />{loading ? <p className="lms-loading">Loading discussion…</p> : items.length ? <div className="lms-discussion-list">{items.map((item) => <DiscussionItem key={item._id} discussion={item} userId={user?._id} onReply={reply} onLike={like} onEdit={edit} onDelete={remove} onLoadReplies={loadReplies} onReplyLike={replyLike} onReplyEdit={replyEdit} onReplyDelete={replyDelete} />)}</div> : <div className="lms-empty"><span>?</span><h3>Start the discussion</h3><p>Be the first student to ask a question about this lesson.</p></div>}</section>
}
