export const MY_COURSES = [
  {
    id: 'fullstack',
    title: 'Full Stack Web Development Bootcamp',
    instructor: 'Rahul Sharma',
    imageType: 'development',
    tint: 'blue',
    status: 'In Progress',
    progress: 65,
    lessons: '48 lessons',
    duration: '56 hours',
  },
  {
    id: 'python-ds',
    title: 'Python for Data Science',
    instructor: 'Ankit Chauhan',
    imageType: 'datascience',
    tint: 'green',
    status: 'In Progress',
    progress: 40,
    lessons: '36 lessons',
    duration: '42 hours',
  },
  {
    id: 'uiux',
    title: 'UI/UX Design Masterclass for Beginners',
    instructor: 'Sneha Patel',
    imageType: 'design',
    tint: 'purple',
    status: 'Not Started',
    progress: 0,
    lessons: '30 lessons',
    duration: '28 hours',
  },
  {
    id: 'ds-ml',
    title: 'Data Science & Machine Learning with Python',
    instructor: 'Priya Verma',
    imageType: 'datascience',
    tint: 'green',
    status: 'Completed',
    progress: 100,
    lessons: '40 lessons',
    duration: '48 hours',
  },
  {
    id: 'marketing',
    title: 'Digital Marketing Fundamentals',
    instructor: 'Tom Baker',
    imageType: 'marketing',
    tint: 'orange',
    status: 'Completed',
    progress: 100,
    lessons: '24 lessons',
    duration: '20 hours',
  },
  {
    id: 'aws',
    title: 'AWS Certified Solutions Architect – Associate',
    instructor: 'Rohit Kumar',
    imageType: 'cloud',
    tint: 'blue',
    status: 'In Progress',
    progress: 20,
    lessons: '52 lessons',
    duration: '60 hours',
  },
]
