// Placeholder order data (mirrors the design reference).
// Swap for API data when order endpoints are ready.

export const ORDERS = [
  {
    id: '#EDU12456',
    course: 'Full Stack Web Development Bootcamp',
    author: 'Rahul Sharma',
    art: 'code',
    tint: 'blue',
    date: '15 Jan 2024',
    time: '10:30 AM',
    amount: '₹3,999',
    payMethod: 'card',
    payLabel: 'Credit Card',
    paySub: '•••• 4242',
    status: 'Completed',
  },
  {
    id: '#EDU12455',
    course: 'Python for Data Analysis for Beginners',
    author: 'Ankit Chauhan',
    art: 'python',
    tint: 'green',
    date: '05 Jan 2024',
    time: '02:15 PM',
    amount: '₹2,999',
    payMethod: 'upi',
    payLabel: 'UPI',
    paySub: 'priya@upi',
    status: 'Completed',
  },
  {
    id: '#EDU12454',
    course: 'Data Science & Machine Learning with Python',
    author: 'Priya Verma',
    art: 'chart',
    tint: 'purple',
    date: '22 Dec 2023',
    time: '11:45 AM',
    amount: '₹3,499',
    payMethod: 'wallet',
    payLabel: 'Paytm Wallet',
    paySub: '•••• 7890',
    status: 'Completed',
  },
  {
    id: '#EDU12453',
    course: 'UI/UX Design Masterclass for Beginners',
    author: 'Sneha Patel',
    art: 'design',
    tint: 'purple',
    date: '10 Dec 2023',
    time: '09:20 AM',
    amount: '₹3,499',
    payMethod: 'card',
    payLabel: 'Credit Card',
    paySub: '•••• 9898',
    status: 'Completed',
  },
  {
    id: '#EDU12452',
    course: 'Digital Marketing Fundamentals',
    author: 'Tom Baker',
    art: 'megaphone',
    tint: 'orange',
    date: '25 Nov 2023',
    time: '04:10 PM',
    amount: '₹2,499',
    payMethod: 'bank',
    payLabel: 'Net Banking',
    paySub: 'HDFC Bank',
    status: 'Completed',
  },
  {
    id: '#EDU12451',
    course: 'AWS Certified Solutions Architect – Associate',
    author: 'Rohit Kumar',
    art: 'cloud',
    tint: 'blue',
    date: '18 Nov 2023',
    time: '01:05 PM',
    amount: '₹5,499',
    payMethod: 'upi',
    payLabel: 'UPI',
    paySub: 'priya@upi',
    status: 'Processing',
  },
]
