import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getAdminCertificate, getAdminCertificatePdfUrl, updateAdminCertificateStatus } from '../../api/admin.js'
import AdminConfirmModal from '../../components/Admin/AdminConfirmModal.jsx'
import AdminIcon from '../../components/Admin/AdminIcons.jsx'
import { useNotifications } from '../../components/Notifications/NotificationProvider.jsx'
import './AdminCertificates.css'

export default function AdminCertificateDetailsPage() {
  const { id } = useParams(); const notifications = useNotifications(); const [certificate, setCertificate] = useState(null); const [error, setError] = useState(null); const [confirming, setConfirming] = useState(false); const [saving, setSaving] = useState(false); const load = useCallback(async () => { setError(null); try { const response = await getAdminCertificate(id); setCertificate(response?.data?.certificate) } catch (requestError) { setError(requestError) } }, [id]); useEffect(() => { load() }, [load]); const toggleStatus = async () => { const next = certificate.status === 'valid' ? 'revoked' : 'valid'; setSaving(true); try { await updateAdminCertificateStatus(id, next); notifications.success(next === 'revoked' ? 'Certificate revoked.' : 'Certificate restored.'); setConfirming(false); await load() } catch (requestError) { notifications.error(requestError?.message || 'Unable to update certificate status.') } finally { setSaving(false) } }
  if (error) return <div className="admin-course-list-state" role="alert"><h2>Unable to load certificate</h2><p>{error?.message || 'Certificate not found.'}</p><Link className="admin-button admin-button--secondary" to="/admin/certificates">Back to certificates</Link></div>; if (!certificate) return <div className="admin-certificate-loading" aria-busy="true"><span className="admin-spinner" />Loading certificate…</div>; const revoked = certificate.status === 'revoked'
  return <div className="admin-certificate-details"><div className="admin-page-heading"><div><Link className="admin-back-link" to="/admin/certificates"><AdminIcon name="arrowLeft" size={17} />Back to certificates</Link><h1>{certificate.certificateNumber}</h1><p>Issued to {certificate.user?.name} for {certificate.course?.title}</p></div><span className={`admin-certificate-status is-${certificate.status}`}>{revoked ? 'Revoked' : 'Valid'}</span></div><section className="admin-certificate-identity"><div><span>Certificate number</span><code>{certificate.certificateNumber}</code></div><div><span>Verification code</span><code>{certificate.verificationCode}</code></div></section><section className="admin-certificate-detail-grid"><article><span>Student</span><h2>{certificate.user?.name}</h2><p>{certificate.user?.email}</p><Link to={`/admin/users/${certificate.user?._id}`}>Open user details</Link></article><article><span>Course</span><h2>{certificate.course?.title}</h2><p>{certificate.course?.instructor} · {certificate.course?.category}</p><Link to={`/admin/courses/${certificate.course?._id}/edit`}>Open course management</Link></article><article><span>Enrollment</span><h2>{certificate.enrollment?.percentageCompleted ?? certificate.enrollment?.progress}% complete</h2><p>Completed {new Date(certificate.completionDate).toLocaleDateString()}</p><Link to={`/admin/enrollments/${certificate.enrollment?._id}`}>Open enrollment details</Link></article></section><section className="admin-certificate-actions"><div><span>Issued</span><strong>{new Date(certificate.issueDate).toLocaleString()}</strong></div><div className="admin-heading-actions"><a className="admin-button admin-button--secondary" href={getAdminCertificatePdfUrl(id)} target="_blank" rel="noreferrer"><AdminIcon name="receipt" size={17} />Open PDF</a><Link className="admin-button admin-button--secondary" to={`/certificate/verify/${certificate.verificationCode}`} target="_blank"><AdminIcon name="shield" size={17} />Verify publicly</Link><button type="button" className={`admin-button ${revoked ? 'admin-button--primary' : 'admin-button--danger'}`} onClick={() => setConfirming(true)}>{revoked ? 'Restore certificate' : 'Revoke certificate'}</button></div></section><p className="admin-certificate-note">Certificate identity, student, course, enrollment, completion date, and verification code are immutable.</p><AdminConfirmModal open={confirming} title={revoked ? 'Restore Certificate?' : 'Revoke Certificate?'} confirmLabel={revoked ? 'Restore certificate' : 'Revoke certificate'} pending={saving} pendingLabel="Saving…" tone={revoked ? 'primary' : 'danger'} icon="shield" onCancel={() => setConfirming(false)} onConfirm={toggleStatus}><p><strong>{certificate.certificateNumber}</strong></p><p>{revoked ? 'Public verification will report this certificate as valid again.' : 'Public verification will report this certificate as revoked. The record and PDF remain preserved.'}</p></AdminConfirmModal></div>
}
