import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getAdminAssignmentSubmission, gradeAdminAssignmentSubmission } from '../../api/admin.js'
import AdminIcon from '../../components/Admin/AdminIcons.jsx'
import { useNotifications } from '../../components/Notifications/NotificationProvider.jsx'
import { assignmentError } from './AdminAssignmentsPage.jsx'
import './AdminAssignments.css'

export default function AdminAssignmentSubmissionDetailsPage() {
  const { id, submissionId } = useParams(); const notifications = useNotifications(); const [data, setData] = useState(null); const [error, setError] = useState(null); const [marks, setMarks] = useState(''); const [remarks, setRemarks] = useState(''); const [saving, setSaving] = useState(false)
  const load = useCallback(async () => { setError(null); try { const response = await getAdminAssignmentSubmission(id, submissionId); const next = response?.data; setData(next); setMarks(next?.submission?.marks ?? ''); setRemarks(next?.submission?.remarks ?? '') } catch (requestError) { setError(requestError) } }, [id, submissionId]); useEffect(() => { load() }, [load]); const save = async (event) => { event.preventDefault(); setSaving(true); try { await gradeAdminAssignmentSubmission(id, submissionId, { marks: Number(marks), remarks }); notifications.success('Submission graded.'); await load() } catch (requestError) { notifications.error(assignmentError(requestError)) } finally { setSaving(false) } }
  if (error) return <div className="admin-course-list-state" role="alert"><h2>Unable to load submission</h2><p>{assignmentError(error)}</p><Link className="admin-button admin-button--secondary" to={`/admin/assignments/${id}/submissions`}>Back to submissions</Link></div>; if (!data) return <div className="admin-assignment-loading" aria-busy="true"><span className="admin-spinner" />Loading submission…</div>; const { assignment, submission } = data
  return <div className="admin-submission-details"><div className="admin-page-heading"><div><Link className="admin-back-link" to={`/admin/assignments/${id}/submissions`}><AdminIcon name="arrowLeft" size={17} />Back to submissions</Link><h1>{submission.student?.name || 'Student submission'}</h1><p>{submission.student?.email} · {assignment.title}</p></div><span className={`admin-review-pill is-${submission.status}`}>{submission.status === 'reviewed' ? 'Reviewed' : 'Submitted'}</span></div><div className="admin-submission-layout"><section className="admin-submission-history"><div className="admin-section-heading"><span>Submission history</span><h2>{submission.versions.length} version{submission.versions.length === 1 ? '' : 's'}</h2></div>{submission.versions.map((version) => <article className="admin-submission-version" key={version._id}><div><strong>Version {version.version}{version.latest ? ' · Latest' : ''}</strong><time dateTime={version.submittedAt}>{new Date(version.submittedAt).toLocaleString()}</time></div><dl><div><dt>Status</dt><dd>{version.status === 'reviewed' ? 'Reviewed' : 'Submitted'}</dd></div><div><dt>Marks</dt><dd>{version.marks ?? 'Not graded'}{version.marks != null ? ` / ${assignment.maxMarks}` : ''}</dd></div></dl>{version.submittedFile?.downloadUrl ? <a className="admin-file-download" href={version.submittedFile.downloadUrl} download={version.submittedFile.originalName}><AdminIcon name="link" size={17} /><span><strong>{version.submittedFile.originalName}</strong><small>{version.submittedFile.mimeType} · {(version.submittedFile.size / 1024).toFixed(1)} KB</small></span>Download</a> : <p>Stored file path is unavailable.</p>}{version.remarks && <div className="admin-version-remarks"><strong>Remarks</strong><p>{version.remarks}</p></div>}</article>)}</section><form className="admin-grade-panel" onSubmit={save}><div className="admin-section-heading"><span>Grading</span><h2>Review latest submission</h2><p>Maximum marks: {assignment.maxMarks}</p></div><label className="admin-field"><span>Marks *</span><input type="number" min="0" max={assignment.maxMarks} step="0.01" value={marks} onChange={(event) => setMarks(event.target.value)} required /></label><label className="admin-field"><span>Feedback / remarks</span><textarea rows="8" maxLength="2000" value={remarks} onChange={(event) => setRemarks(event.target.value)} placeholder="Share clear feedback with the learner." /></label><button type="submit" className="admin-button admin-button--primary" disabled={saving}>{saving ? 'Saving grade…' : 'Save grade'}</button><p className="admin-grade-note">Saving sets the existing submission status to Reviewed. Uploaded files, ownership, and timestamps are unchanged.</p></form></div></div>
}
