import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { createAdminQuiz, createAdminQuizQuestion, deleteAdminQuizQuestion, getAdminQuiz, getAdminQuizOptions, reorderAdminQuizQuestions, updateAdminQuiz, updateAdminQuizQuestion } from '../../api/admin.js'
import AdminConfirmModal from '../../components/Admin/AdminConfirmModal.jsx'
import AdminIcon from '../../components/Admin/AdminIcons.jsx'
import AdminQuizQuestionEditor, { blankQuestion } from '../../components/Admin/AdminQuizQuestionEditor.jsx'
import { useNotifications } from '../../components/Notifications/NotificationProvider.jsx'
import './AdminQuizzes.css'

const blankQuiz = { title: '', course: '', moduleId: '', lessonId: '', passingMarks: 60, timeLimit: 10, isPublished: true }
const errorCopy = (error) => error?.status === 409 ? error.message : error?.status === 400 ? error?.errors?.[0]?.message || error.message : error?.status === 404 ? 'The requested quiz or curriculum item was not found.' : error?.code === 'NETWORK' || error?.code === 'OFFLINE' ? 'Unable to reach the server. Check your connection and retry.' : error?.message || 'Unable to save the quiz.'
const questionPayload = (question, lockAnswers = false) => ({ question: question.question.trim(), explanation: question.explanation.trim(), difficulty: question.difficulty, ...(lockAnswers ? {} : { options: question.options.map((option) => option.trim()), correctAnswer: Number(question.correctAnswer) }) })

export default function AdminQuizFormPage({ mode }) {
  const editing = mode === 'edit'; const { id } = useParams(); const navigate = useNavigate(); const notifications = useNotifications()
  const [form, setForm] = useState(blankQuiz); const [questions, setQuestions] = useState(editing ? [] : [blankQuestion()]); const [courses, setCourses] = useState([])
  const [attemptCount, setAttemptCount] = useState(0); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(null); const [saving, setSaving] = useState(false); const [savingQuestion, setSavingQuestion] = useState(null); const [deleteQuestion, setDeleteQuestion] = useState(null); const [reordering, setReordering] = useState(false)
  const structuralLocked = editing && attemptCount > 0

  useEffect(() => { let active = true; Promise.all([getAdminQuizOptions(), editing ? getAdminQuiz(id) : Promise.resolve(null)]).then(([optionsResponse, quizResponse]) => { if (!active) return; setCourses(optionsResponse?.data?.courses ?? []); if (editing) { const quiz = quizResponse?.data?.quiz; setForm({ title: quiz.title, course: quiz.course, moduleId: quiz.moduleId, lessonId: quiz.lessonId, passingMarks: quiz.passingMarks, timeLimit: quiz.timeLimit, isPublished: quiz.isPublished }); setQuestions(quiz.questions ?? []); setAttemptCount(quiz.attemptCount ?? 0) } }).catch((error) => active && setLoadError(error)).finally(() => active && setLoading(false)); return () => { active = false } }, [editing, id])
  const selectedCourse = useMemo(() => courses.find((course) => course._id === form.course), [courses, form.course])
  const modules = selectedCourse?.modules ?? []; const selectedModule = modules.find((module) => module.moduleId === form.moduleId); const lessons = selectedModule?.lessons ?? []
  const setField = (field, value) => setForm((current) => ({ ...current, [field]: value }))
  const selectCourse = (value) => setForm((current) => ({ ...current, course: value, moduleId: '', lessonId: '' }))
  const selectModule = (value) => setForm((current) => ({ ...current, moduleId: value, lessonId: '' }))
  const changeQuestion = (index, question) => setQuestions((current) => current.map((item, currentIndex) => currentIndex === index ? question : item))
  const validateQuestion = (question) => question.question.trim() && question.explanation.trim() && question.options.every((option) => option.trim()) && new Set(question.options.map((option) => option.trim().toLowerCase())).size === 4

  const saveQuiz = async (event) => { event.preventDefault(); if (!form.course || !form.moduleId || !form.lessonId) { notifications.error('Select a course, module, and lesson.'); return } if (!editing && (!questions.length || questions.some((question) => !validateQuestion(question)))) { notifications.error('Complete every question, explanation, and four unique options.'); return } setSaving(true); try { const payload = { ...form, passingMarks: Number(form.passingMarks), timeLimit: Number(form.timeLimit) }; if (!editing) payload.questions = questions.map((question) => questionPayload(question)); const response = editing ? await updateAdminQuiz(id, payload) : await createAdminQuiz(payload); const quizId = response?.data?.quiz?._id || id; notifications.success(editing ? 'Quiz updated.' : 'Quiz created.'); navigate(`/admin/quizzes/${quizId}`) } catch (error) { notifications.error(errorCopy(error)) } finally { setSaving(false) } }

  const saveQuestion = async (index) => { const question = questions[index]; if (!validateQuestion(question)) { notifications.error('Complete the question, explanation, and four unique options.'); return } setSavingQuestion(question._id || `new-${index}`); try { const response = question._id ? await updateAdminQuizQuestion(id, question._id, questionPayload(question, structuralLocked)) : await createAdminQuizQuestion(id, questionPayload(question)); const saved = response?.data?.question; changeQuestion(index, saved ?? question); notifications.success(question._id ? 'Question updated.' : 'Question added.') } catch (error) { notifications.error(errorCopy(error)) } finally { setSavingQuestion(null) } }
  const moveQuestion = async (index, direction) => { const target = index + direction; if (target < 0 || target >= questions.length) return; const next = [...questions]; [next[index], next[target]] = [next[target], next[index]]; if (!editing) { setQuestions(next); return } if (next.some((question) => !question._id)) { notifications.error('Save new questions before reordering.'); return } setReordering(true); try { const response = await reorderAdminQuizQuestions(id, next.map((question) => question._id)); setQuestions(response?.data?.questions ?? next); notifications.success('Questions reordered.') } catch (error) { notifications.error(errorCopy(error)) } finally { setReordering(false) } }
  const confirmQuestionDelete = async () => { if (!deleteQuestion) return; const index = questions.findIndex((question) => question === deleteQuestion); if (!deleteQuestion._id) { setQuestions((current) => current.filter((question) => question !== deleteQuestion)); setDeleteQuestion(null); return } setSavingQuestion(deleteQuestion._id); try { await deleteAdminQuizQuestion(id, deleteQuestion._id); setQuestions((current) => current.filter((question) => question._id !== deleteQuestion._id)); notifications.success('Question deleted.'); setDeleteQuestion(null) } catch (error) { notifications.error(errorCopy(error)); setDeleteQuestion(null) } finally { setSavingQuestion(null) } }

  if (loading) return <div className="admin-quiz-form-state" aria-busy="true"><span className="admin-spinner" />Loading quiz editor…</div>
  if (loadError) return <div className="admin-course-list-state" role="alert"><h2>Unable to load quiz editor</h2><p>{errorCopy(loadError)}</p><Link className="admin-button admin-button--secondary" to="/admin/quizzes">Back to quizzes</Link></div>

  return <div className="admin-quiz-form-page"><div className="admin-page-heading"><div><Link className="admin-back-link" to={editing ? `/admin/quizzes/${id}` : '/admin/quizzes'}><AdminIcon name="arrowLeft" size={17} />Back to quizzes</Link><h1>{editing ? 'Edit Quiz' : 'Create Quiz'}</h1><p>{editing ? 'Update settings and manage embedded questions.' : 'Attach a new assessment to a curriculum lesson.'}</p></div></div>
    {structuralLocked && <section className="admin-integrity-banner" role="status"><AdminIcon name="shield" /><div><strong>Learner history is protected</strong><p>{attemptCount} attempt{attemptCount === 1 ? '' : 's'} exist. Attachment, passing score, time limit, options, correct answers, question order, and deletions are locked. Titles, availability, wording, explanations, and difficulty remain editable.</p></div></section>}
    <form className="admin-quiz-form" onSubmit={saveQuiz}><section className="admin-form-card"><div className="admin-form-card__heading"><div><span>Quiz settings</span><h2>Basic information</h2></div><span className={`admin-status-pill ${form.isPublished ? 'is-published' : 'is-draft'}`}>{form.isPublished ? 'Published' : 'Draft'}</span></div><div className="admin-form-grid"><label className="admin-field admin-field--wide"><span>Quiz title *</span><input value={form.title} onChange={(event) => setField('title', event.target.value)} maxLength="160" required /></label><label className="admin-field"><span>Course *</span><select value={form.course} onChange={(event) => selectCourse(event.target.value)} disabled={structuralLocked} required><option value="">Select course</option>{courses.map((course) => <option key={course._id} value={course._id}>{course.title}</option>)}</select></label><label className="admin-field"><span>Module *</span><select value={form.moduleId} onChange={(event) => selectModule(event.target.value)} disabled={!form.course || structuralLocked} required><option value="">Select module</option>{modules.map((module) => <option key={module.moduleId} value={module.moduleId}>{module.title}</option>)}</select></label><label className="admin-field"><span>Lesson *</span><select value={form.lessonId} onChange={(event) => setField('lessonId', event.target.value)} disabled={!form.moduleId || structuralLocked} required><option value="">Select lesson</option>{lessons.map((lesson) => <option key={lesson.lessonId} value={lesson.lessonId}>{lesson.title}</option>)}</select></label><label className="admin-field"><span>Passing score (%) *</span><input type="number" min="1" max="100" value={form.passingMarks} onChange={(event) => setField('passingMarks', event.target.value)} disabled={structuralLocked} required /></label><label className="admin-field"><span>Time limit (minutes) *</span><input type="number" min="1" max="180" value={form.timeLimit} onChange={(event) => setField('timeLimit', event.target.value)} disabled={structuralLocked} required /></label><label className="admin-switch-field"><input type="checkbox" checked={form.isPublished} onChange={(event) => setField('isPublished', event.target.checked)} /><span><strong>Available to students</strong><small>Draft quizzes remain hidden from the student API.</small></span></label></div><div className="admin-form-card__actions"><Link className="admin-button admin-button--secondary" to={editing ? `/admin/quizzes/${id}` : '/admin/quizzes'}>Cancel</Link><button className="admin-button admin-button--primary" type="submit" disabled={saving}>{saving ? 'Saving quiz…' : editing ? 'Save settings' : 'Create quiz'}</button></div></section></form>
    <section className="admin-question-section"><div className="admin-question-section__heading"><div><span>Question editor</span><h2>Questions ({questions.length})</h2><p>Each question requires exactly four unique options. Select the correct answer with its radio button.</p></div><button type="button" className="admin-button admin-button--secondary" onClick={() => setQuestions((current) => [...current, blankQuestion()])} disabled={structuralLocked}><AdminIcon name="plus" size={17} />Add question</button></div>
      {questions.length === 0 ? <div className="admin-question-empty"><h3>No questions yet</h3><p>Add a question before publishing this quiz.</p></div> : questions.map((question, index) => <AdminQuizQuestionEditor key={question._id || `new-${index}`} question={question} index={index} total={questions.length} locked={structuralLocked} saving={savingQuestion === (question._id || `new-${index}`) || reordering} onChange={(value) => changeQuestion(index, value)} onSave={editing ? () => saveQuestion(index) : null} onMove={(direction) => moveQuestion(index, direction)} onDelete={questions.length > 1 || editing ? () => setDeleteQuestion(question) : null} />)}
    </section><AdminConfirmModal open={Boolean(deleteQuestion)} title="Delete Question?" confirmLabel="Delete question" pending={savingQuestion === deleteQuestion?._id} onCancel={() => setDeleteQuestion(null)} onConfirm={confirmQuestionDelete}><p>This question will be removed from the quiz.</p><p>Questions referenced by learner attempts are protected.</p></AdminConfirmModal></div>
}
