import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getAdminAssignment, getAdminAssignmentSubmissions } from '../../api/admin.js'
import AdminIcon from '../../components/Admin/AdminIcons.jsx'
import AdminSubmissionTable from '../../components/Admin/AdminSubmissionTable.jsx'
import { assignmentError } from './AdminAssignmentsPage.jsx'
import './AdminAssignments.css'

export default function AdminAssignmentSubmissionsPage() {
  const { id } = useParams(); const requestId = useRef(0); const [assignment, setAssignment] = useState(null); const [search, setSearch] = useState(''); const [debounced, setDebounced] = useState(''); const [status, setStatus] = useState(''); const [sort, setSort] = useState('newest'); const [page, setPage] = useState(1); const [submissions, setSubmissions] = useState([]); const [pagination, setPagination] = useState({ total: 0, page: 1, pages: 1, limit: 10 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(null)
  useEffect(() => { getAdminAssignment(id).then((response) => setAssignment(response?.data?.assignment)).catch(setError) }, [id]); useEffect(() => { const timer = setTimeout(() => { setDebounced(search.trim()); setPage(1) }, 300); return () => clearTimeout(timer) }, [search]); const query = useMemo(() => ({ search: debounced, status, sort, page, limit: 10 }), [debounced, status, sort, page]); const load = useCallback(async () => { const current = ++requestId.current; setLoading(true); setError(null); try { const response = await getAdminAssignmentSubmissions(id, query); if (current !== requestId.current) return; setSubmissions(response?.data?.submissions ?? []); setPagination(response?.data?.pagination ?? {}) } catch (requestError) { if (current === requestId.current) setError(requestError) } finally { if (current === requestId.current) setLoading(false) } }, [id, query]); useEffect(() => { load(); return () => { requestId.current += 1 } }, [load]); const filtered = Boolean(debounced || status || sort !== 'newest'); const clear = () => { setSearch(''); setDebounced(''); setStatus(''); setSort('newest'); setPage(1) }
  return <div className="admin-assignment-submissions"><div className="admin-page-heading"><div><Link className="admin-back-link" to={`/admin/assignments/${id}`}><AdminIcon name="arrowLeft" size={17} />Back to assignment</Link><h1>Submissions</h1><p>{assignment ? `Assignment: ${assignment.title}` : 'Review learner work and grading status.'}</p></div></div><section className="admin-assignment-manager"><div className="admin-submission-toolbar"><label className="admin-course-search"><span className="sr-only">Search students</span><AdminIcon name="search" size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search student name or email…" /></label><select aria-label="Filter submission status" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }}><option value="">All statuses</option><option value="submitted">Submitted</option><option value="reviewed">Reviewed</option></select><select aria-label="Sort submissions" value={sort} onChange={(event) => { setSort(event.target.value); setPage(1) }}><option value="newest">Newest submission</option><option value="oldest">Oldest submission</option><option value="studentAsc">Student A–Z</option><option value="marksDesc">Marks high–low</option><option value="marksAsc">Marks low–high</option></select></div><div className="admin-course-manager__heading"><div><h2>Learner submissions</h2><p>{pagination.total || 0} submission{pagination.total === 1 ? '' : 's'}</p></div>{filtered && <button type="button" onClick={clear}>Clear filters</button>}</div>{loading ? <div className="admin-course-table-loading" aria-busy="true">{Array.from({ length: 5 }, (_, index) => <span key={index} />)}</div> : error ? <div className="admin-course-list-state" role="alert"><h3>Unable to load submissions</h3><p>{assignmentError(error)}</p><button type="button" className="admin-button admin-button--primary" onClick={load}>Retry</button></div> : submissions.length === 0 ? <div className="admin-course-list-state"><h3>{filtered ? 'No submissions match your filters.' : 'No submissions yet.'}</h3><p>Learner submissions will appear here.</p></div> : <AdminSubmissionTable assignmentId={id} submissions={submissions} />}{!loading && !error && pagination.total > 0 && <div className="admin-pagination"><span>Page {page} of {pagination.pages}</span><div><button type="button" onClick={() => setPage((value) => value - 1)} disabled={page <= 1}>Previous</button><button type="button" onClick={() => setPage((value) => value + 1)} disabled={page >= pagination.pages}>Next</button></div></div>}</section></div>
}
