import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { getAdminAssignment } from '../../api/admin.js'
import AdminIcon from '../../components/Admin/AdminIcons.jsx'
import { assignmentError } from './AdminAssignmentsPage.jsx'
import './AdminAssignments.css'

const safeUrl = (url) => /^https?:\/\//i.test(url) || url?.startsWith('/') ? url : null
export default function AdminAssignmentDetailsPage() {
  const { id } = useParams(); const [assignment, setAssignment] = useState(null); const [error, setError] = useState(null); useEffect(() => { let active = true; getAdminAssignment(id).then((response) => active && setAssignment(response?.data?.assignment)).catch((requestError) => active && setError(requestError)); return () => { active = false } }, [id]); if (error) return <div className="admin-course-list-state" role="alert"><h2>Unable to load assignment</h2><p>{assignmentError(error)}</p><Link className="admin-button admin-button--secondary" to="/admin/assignments">Back to assignments</Link></div>; if (!assignment) return <div className="admin-assignment-loading" aria-busy="true"><span className="admin-spinner" />Loading assignment…</div>
  return <div className="admin-assignment-details"><div className="admin-page-heading"><div><Link className="admin-back-link" to="/admin/assignments"><AdminIcon name="arrowLeft" size={17} />Back to assignments</Link><h1>{assignment.title}</h1><p>{assignment.courseTitle} · {assignment.moduleTitle} · {assignment.lessonTitle}</p></div><div className="admin-heading-actions"><Link className="admin-button admin-button--secondary" to={`/admin/assignments/${id}/submissions`}><AdminIcon name="users" size={17} />Submissions</Link><Link className="admin-button admin-button--primary" to={`/admin/assignments/${id}/edit`}><AdminIcon name="edit" size={17} />Edit</Link></div></div><section className="admin-assignment-detail-stats">{[['Availability', assignment.isPublished ? 'Published' : 'Draft'], ['Due date', new Date(assignment.dueDate).toLocaleDateString()], ['Maximum marks', assignment.maxMarks], ['Submissions', assignment.submissionCount], ['Graded', assignment.gradedCount], ['Average marks', assignment.averageMarks]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section>{assignment.submissionCount > 0 && <section className="admin-integrity-banner"><AdminIcon name="shield" /><div><strong>Submission history protected</strong><p>Structural assignment changes and deletion are restricted.</p></div></section>}<section className="admin-assignment-copy"><div><span>Description</span><p>{assignment.description}</p></div><div><span>Instructions</span><p>{assignment.instructions}</p></div><div><span>Instructor resources</span>{assignment.attachments.length ? <ul>{assignment.attachments.map((item, index) => <li key={`${item.title}-${index}`}>{safeUrl(item.url) ? <a href={item.url} target={item.url.startsWith('http') ? '_blank' : undefined} rel="noreferrer">{item.title} <small>{item.type}</small></a> : <span>{item.title} — unavailable URL</span>}</li>)}</ul> : <p>No instructor resources.</p>}</div></section><p className="admin-detail-dates">Created {new Date(assignment.createdAt).toLocaleString()} · Updated {new Date(assignment.updatedAt).toLocaleString()}</p></div>
}
